set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

if(NOT DEFINED ENV{CROSS_COMPILE})
  message(FATAL_ERROR "Set CROSS_COMPILE to the full arm-linux-gnueabihf- prefix")
endif()

set(CMAKE_C_COMPILER "$ENV{CROSS_COMPILE}gcc")
set(CMAKE_CXX_COMPILER "$ENV{CROSS_COMPILE}g++")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

